packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.19.0
  "@eslint/eslintrc": ^3
  prettier: ^3.4.2
  tailwindcss: ^4
  "@tailwindcss/postcss": ^4
  typescript: ^5.7.3

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
